---
name: ansible-base
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ansible-base.yml
jobs:
  build_ansible_base:
    name: Build ansible-base
    runs-on: ubuntu-20.04
    steps:
      - name: setup
        env:
          DPUT_CF: ${{ secrets.DPUT_CF }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSPHRASE: ${{ secrets.SIGNING_PASSPHRASE }}
          SIGNING_OWNERTRUST: ${{ secrets.SIGNING_OWNERTRUST }}
        run: |
          sudo apt -y install wget gpg gpg-agent

          sudo apt -y remove ansible || true
          sudo apt -y remove ansible-base || true
          sudo apt -y remove ansible-core || true
          sudo apt -y remove ansible-test || true
          sudo apt -y autoremove

          echo "${DPUT_CF}" > ${HOME}/.dput.cf
          echo "${SIGNING_KEY}" > ${HOME}/signing.key
          echo "${SIGNING_PASSPHRASE}" > ${HOME}/signing.passphrase
          echo "${SIGNING_OWNERTRUST}" > ${HOME}/signing.ownertrust

          gpg --import --batch --pinentry-mode loopback --passphrase-file ${HOME}/signing.passphrase ${HOME}/signing.key
          gpg --import-ownertrust --batch --pinentry-mode loopback --passphrase-file ${HOME}/signing.passphrase ${HOME}/signing.ownertrust
          gpg --list-secret-keys --keyid-format LONG

      - name: build
        env:
          DEB_NAME: ansible-base
          DEB_VERSION: "2.10.5"
          DEB_RELEASE: 5ppa
          DEB_DIST: groovy focal bionic
          DEB_PPA: ansible
          DEBSIGN_KEYID: ${{ secrets.DEBSIGN_KEYID }}
          OFFICIAL: yes
          TARBALL_URL: https://files.pythonhosted.org/packages/bf/44/a75eec7928986a48e179769873f282496e007587e112c57d367c5e1abc1a/ansible-base-2.10.5.tar.gz
          DEBUILD_ADD_OPTS: '-p"gpg --pinentry-mode loopback --passphrase-file ${HOME}/signing.passphrase"'
        run: |
          sudo apt -y install make python python-packaging python-setuptools python3-straight.plugin python3-jinja2 python3-yaml python3-docutils devscripts cdbs debhelper dh-python python3-setuptools python3-packaging

          cd ${HOME}
          wget ${TARBALL_URL}
          rm -rf ${DEB_NAME}-${DEB_VERSION}
          tar -xzf ${DEB_NAME}-${DEB_VERSION}.tar.gz
          cd ${HOME}/${DEB_NAME}-${DEB_VERSION}
          sed -i 's/^DEBUILD = $(DEBUILD_BIN) $(DEBUILD_OPTS)$/DEBUILD_ADD_OPTS ?=\nDEBUILD = $(DEBUILD_BIN) $(DEBUILD_OPTS) $(DEBUILD_ADD_OPTS)/g' Makefile
          time make deb-src-upload
